import create from 'zustand'


const useStore = create((set) => ({
    lentilCount: 0,
    incLentil: () => set((state) => ({ lentilCount: state.lentilCount + 1 })),
    decLentil: () => set((state) => ({ lentilCount: state.lentilCount - 1 })),
    lentilCountL: 0,
    incLentilL: () => set((state) => ({ lentilCountL: state.lentilCountL + 1 })),
    decLentilL: () => set((state) => ({ lentilCountL: state.lentilCountL - 1 })),
    chickCount: 0,
    incChick: () => set((state) => ({ chickCount: state.chickCount + 1 })),
    decChick: () => set((state) => ({ chickCount: state.chickCount - 1 })),
    chickCountL: 0,
    incChickL: () => set((state) => ({ chickCountL: state.chickCountL + 1 })),
    decChickL: () => set((state) => ({ chickCountL: state.chickCountL - 1 })),
    rBeanCount: 0,
    incRbean: () => set((state) => ({ rBeanCount: state.rBeanCount + 1 })),
    decRbean: () => set((state) => ({ rBeanCount: state.rBeanCount - 1 })),
    rBeanCountL: 0,
    incRbeanL: () => set((state) => ({ rBeanCountL: state.rBeanCountL + 1 })),
    decRbeanL: () => set((state) => ({ rBeanCountL: state.rBeanCountL - 1 })),
    wBeanCount: 0,
    incWbean: () => set((state) => ({ wBeanCount: state.wBeanCount + 1 })),
    decWbean: () => set((state) => ({ wBeanCount: state.wBeanCount - 1 })),
    wBeanCountL: 0,
    incWbeanL: () => set((state) => ({ wBeanCountL: state.wBeanCountL + 1 })),
    decWbeanL: () => set((state) => ({ wBeanCountL: state.wBeanCountL - 1 })),
    blackEyedCount: 0,
    incBlackEyed: () => set((state) => ({ blackEyedCount: state.blackEyedCount + 1 })),
    decBlackEyed: () => set((state) => ({ blackEyedCount: state.blackEyedCount - 1 })),
    blackEyedCountL: 0,
    incBlackEyedL: () => set((state) => ({ blackEyedCountL: state.blackEyedCountL + 1 })),
    decBlackEyedL: () => set((state) => ({ blackEyedCountL: state.blackEyedCountL - 1 })),
    matterDalCount: 0,
    incMatterDal: () => set((state) => ({ matterDalCount: state.matterDalCount + 1 })),
    decMatterDal: () => set((state) => ({ matterDalCount: state.matterDalCount - 1 })),
    matterDalCountL: 0,
    incMatterDalL: () => set((state) => ({ matterDalCountL: state.matterDalCountL + 1 })),
    decMatterDalL: () => set((state) => ({ matterDalCountL: state.matterDalCountL - 1 })),
    popcornCount: 0,
    incPopcorn: () => set((state) => ({ popcornCount: state.popcornCount + 1 })),
    decPopcorn: () => set((state) => ({ popcornCount: state.popcornCount - 1 })),
    popcornCountL: 0,
    incPopcornL: () => set((state) => ({ popcornCountL: state.popcornCountL + 1 })),
    decPopcornL: () => set((state) => ({ popcornCountL: state.popcornCountL - 1 })),
    cashewCount: 0,
    incCashew: () => set((state) => ({ cashewCount: state.cashewCount + 1 })),
    decCashew: () => set((state) => ({ cashewCount: state.cashewCount - 1 })),
    cashewCountL: 0,
    incCashewL: () => set((state) => ({ cashewCountL: state.cashewCountL + 1 })),
    decCashewL: () => set((state) => ({ cashewCountL: state.cashewCountL - 1 })),
    almondCount: 0,
    incAlmond: () => set((state) => ({ almondCount: state.almondCount + 1 })),
    decAlmond: () => set((state) => ({ almondCount: state.almondCount - 1 })),
    almondCountL: 0,
    incAlmondL: () => set((state) => ({ almondCountL: state.almondCountL + 1 })),
    decAlmondL: () => set((state) => ({ almondCountL: state.almondCountL - 1 })),
    pistachioCount: 0,
    incPistachio: () => set((state) => ({ pistachioCount: state.pistachioCount + 1 })),
    decPistachio: () => set((state) => ({ pistachioCount: state.pistachioCount - 1 })),
    pistachioCountL: 0,
    incPistachioL: () => set((state) => ({ pistachioCountL: state.pistachioCountL + 1 })),
    decPistachioL: () => set((state) => ({ pistachioCountL: state.pistachioCountL - 1 })),
  }))


export default useStore